# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
