# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181013_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 15, 50, 50, 839303, tzinfo=utc)),
        ),
    ]
