# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181015_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 13, 14, 31, 445245, tzinfo=utc)),
        ),
    ]
