# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20181015_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_average',
        ),
        migrations.AddField(
            model_name='review',
            name='average',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 13, 30, 28, 351159, tzinfo=utc)),
        ),
    ]
