# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20181015_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 14, 10, 42, 882283, tzinfo=utc)),
        ),
    ]
