# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20181016_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 17, 5, 44, 24, 237993, tzinfo=utc)),
        ),
    ]
