# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20181017_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 17, 8, 9, 46, 861799, tzinfo=utc)),
        ),
    ]
